version: '2'

services:
    postgres:
        image: vtycloud/postgres
        container_name: db
        ports:
        - "5435:5432"
        volumes:
        - ./data/db:/var/lib/postgresql/data

    solr:
        image: vtycloud/dvndarasolr
        container_name: solr
        ports:
        - "8985:8983"
        environment:
          - "SOLR_HOST=solr"
        volumes:
        - ./data/solr:/usr/local/solr-4.6.0/example/solr/collection1/data

    dataverse:
        image: vtycloud/dvndara
#        container_name: dataverse
        build: dataversedock
        ports:
        - "443:443"
        - "8085:8080"
        environment:
          - "SITEURL=test.dataverse.cessda.eu"
          - "HOST_DNS_ADDRESS=0.0.0.0"
          - "LANG=en"
          - "BUNDLEPROPERTIES=Bundle.properties"
          - "GLASSFISH_DIRECTORY=/opt/glassfish4"
          - "ADMIN_EMAIL=vyacheslav.tykhonov@dans.knaw.nl"
          - "FROM_EMAIL=vty@dans.knaw.nl"
          - "MAIL_SERVER=mailrelay.knaw.nl"
          - "POSTGRES_ADMIN_PASSWORD=secret"
          - "POSTGRES_SERVER=postgres"
          - "POSTGRES_PORT=5432"
          - "POSTGRES_DATABASE=dvndb"
          - "POSTGRES_USER=dvnapp"
          - "POSTGRES_PASSWORD=secret"
          - "SOLR_LOCATION=solr:8983"
          - "TWORAVENS_LOCATION=NOT INSTALLED"
          - "RSERVE_HOST=localhost"
          - "RSERVE_PORT=6311"
          - "RSERVE_USER=rserve"
          - "RSERVE_PASSWORD=rserve"
          - "doiprovider=dara-4.0"
          - "authority=10.5072"
          - "DOIseparator=/"
          - "baseuri=http://labs.da-ra.de"
          - "DEBUG=yes"
        depends_on:
          - postgres
          - solr
        volumes:
        - ./data/dataverse:/usr/local/glassfish4/glassfish/domains/domain1/files
networks:
  dvn:
    driver: bridge
